#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────
#
# Provisions the Google Cloud side of docs/SPEC.md from zero.
#
#   bash deploy/gcp/setup.sh
#
# Two things this exists for beyond saving typing:
#
#   1. Billing is a SUBMISSION REQUIREMENT, not a precaution. Measured
#      2026-09-07: the Gemini free tier is 5 RPM and one job is 4-5 calls, so a
#      single run nearly exhausts the minute and a judge running the demo while
#      anything else is in flight gets a 429. Stage 3 is the whole reason this
#      script is worth having.
#   2. It ends by actually calling Cloud TTS and writing to the bucket, because
#      "the console says it is enabled" and "the app can use it" are different
#      claims and only the second one matters on demo day.
#
# Safe to re-run. Every step checks for what already exists, and values already
# in .env.development come back as the default (press Enter to keep).

# This project has no bare `.env` — config reads .env.<NODE_ENV>. The real key
# lives here, and .gitignore keeps it out of a repo that becomes public.
ENV_FILE=".env.development"

TOTAL_STAGES=8

banner "Google Cloud setup · Intent-Preserving Localization"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "The gcloud CLI"
say "Everything after this drives gcloud, so it has to exist and be logged in."
printf '\n'

if command -v gcloud >/dev/null 2>&1; then
  note "found $(gcloud --version 2>/dev/null | head -1)"
else
  warn "gcloud is not on PATH."
  say "Install it, then re-run this script:"
  printf '\n'
  note "  Debian/Ubuntu/WSL:"
  note "    curl https://sdk.cloud.google.com | bash && exec -l \$SHELL"
  note "  macOS:"
  note "    brew install --cask google-cloud-sdk"
  printf '\n'
  open_url "https://cloud.google.com/sdk/docs/install"
  exit 1
fi

if gcloud auth list --filter=status:ACTIVE --format="value(account)" 2>/dev/null | grep -q .; then
  note "signed in as $(gcloud auth list --filter=status:ACTIVE --format='value(account)' | head -1)"
  if ! confirm "Use this account?"; then
    say "Running: gcloud auth login"
    gcloud auth login
  fi
else
  say "Not signed in. A browser window will open."
  pause "Press Enter to run: gcloud auth login"
  gcloud auth login
fi

pause "Done. Press Enter for the next stage."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "The GCP project"
say "An AI Studio key always belongs to a Google Cloud project, and billing is"
say "enabled per project. So the key and the billing have to end up on the SAME"
say "project or the rate limit never lifts."
printf '\n'
step "Open the AI Studio key page and look at the 'Project' column for your key."
open_url "https://aistudio.google.com/apikey"
printf '\n'
say "Either paste that project's ID to reuse it, or type a NEW id to create one"
say "(lowercase letters, digits and hyphens; 6-30 chars; globally unique)."
printf '\n'

ask GCP_PROJECT_ID "Project ID:"
while [[ -z "${GCP_PROJECT_ID}" ]]; do
  warn "A project ID is required."
  ask GCP_PROJECT_ID "Project ID:"
done

if gcloud projects describe "$GCP_PROJECT_ID" >/dev/null 2>&1; then
  note "project $GCP_PROJECT_ID exists — reusing it"
else
  warn "No project '$GCP_PROJECT_ID' is visible to this account."
  if confirm "Create it now?"; then
    if gcloud projects create "$GCP_PROJECT_ID" \
         --name="Intent-Preserving Localization"; then
      note "created $GCP_PROJECT_ID"
    else
      warn "Could not create it. Project IDs are globally unique — try another."
      exit 1
    fi
  else
    say "Nothing else can proceed without a project. Re-run when you have one."
    exit 1
  fi
fi

gcloud config set project "$GCP_PROJECT_ID" >/dev/null 2>&1 || true
write_env GOOGLE_CLOUD_PROJECT "$GCP_PROJECT_ID"
pause "Press Enter for the next stage."

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Billing — the 5 RPM fix"
say "This is the stage that matters. On the free tier gemini-3.8-flash allows"
say "5 requests per minute; one localization job is 4-5 Gemini calls. A judge"
say "running the demo hits 429 on the second job. Linking billing moves the key"
say "to Tier 1 and the limit stops being a demo risk."
printf '\n'

CURRENT_BILLING=$(gcloud billing projects describe "$GCP_PROJECT_ID" \
  --format="value(billingEnabled)" 2>/dev/null || echo "")

if [[ "$CURRENT_BILLING" == "True" ]]; then
  note "billing is already enabled on $GCP_PROJECT_ID — nothing to do"
else
  say "Available billing accounts:"
  printf '\n'
  gcloud billing accounts list 2>/dev/null || warn "could not list billing accounts"
  printf '\n'
  say "If that list is empty you need to create one (free trial credits count)."
  step "Create or find a billing account in the console."
  open_url "https://console.cloud.google.com/billing"
  printf '\n'
  ask GCP_BILLING_ACCOUNT "Billing account ID (looks like 01ABCD-234567-89EFGH):"

  if [[ -n "$GCP_BILLING_ACCOUNT" ]]; then
    if gcloud billing projects link "$GCP_PROJECT_ID" \
         --billing-account="$GCP_BILLING_ACCOUNT" >/dev/null 2>&1; then
      note "linked billing to $GCP_PROJECT_ID"
    else
      warn "Linking failed. Link it by hand in the console, then re-run."
      SKIPPED+=("link billing account to $GCP_PROJECT_ID")
    fi
  else
    warn "Skipped. The demo will run on the 5 RPM free tier until this is done."
    SKIPPED+=("enable billing on $GCP_PROJECT_ID (submission requirement)")
  fi
fi

pause "Press Enter for the next stage."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Enable the APIs"
say "Cloud Text-to-Speech synthesizes the Hindi audio (stage 4 of the"
say "pipeline); Cloud Storage holds every upload and output."
printf '\n'
say "Enabling: texttospeech.googleapis.com, storage.googleapis.com"

if gcloud services enable texttospeech.googleapis.com storage.googleapis.com \
     --project="$GCP_PROJECT_ID"; then
  note "enabled"
else
  warn "Enabling failed — usually means billing is not linked yet."
  SKIPPED+=("enable texttospeech + storage APIs")
fi

printf '\n'
say "Phase 5 deploys the API and web app to Cloud Run. Enabling those APIs now"
say "costs nothing and saves a stall on deploy day."
if confirm "Also enable Cloud Run, Cloud Build and Artifact Registry?"; then
  gcloud services enable run.googleapis.com cloudbuild.googleapis.com \
    artifactregistry.googleapis.com --project="$GCP_PROJECT_ID" \
    || warn "could not enable the Phase 5 APIs; do it before deploying"
fi

pause "Press Enter for the next stage."

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "The GCS bucket"
say "Holds jobs/<jobId>/source.mp3 and output.mp3. Bucket names are globally"
say "unique, so '<something>-localize' with your initials is a safe shape."
printf '\n'

ask GCS_BUCKET "Bucket name (no gs:// prefix):"
while [[ -z "${GCS_BUCKET}" ]]; do
  warn "A bucket name is required."
  ask GCS_BUCKET "Bucket name (no gs:// prefix):"
done

ask GCP_REGION "Region [asia-south1 for India, Enter accepts]:"
[[ -z "$GCP_REGION" ]] && GCP_REGION="asia-south1"

if gcloud storage buckets describe "gs://${GCS_BUCKET}" >/dev/null 2>&1; then
  note "bucket gs://${GCS_BUCKET} already exists — reusing it"
else
  # Uniform bucket-level access: no per-object ACLs, so the only way to reach a
  # file is IAM. The API streams audio to the browser itself, with Range support
  # (SPEC section b, amended in Phase 4), so nothing here ever needs to be public.
  if gcloud storage buckets create "gs://${GCS_BUCKET}" \
       --location="$GCP_REGION" \
       --uniform-bucket-level-access \
       --project="$GCP_PROJECT_ID"; then
    note "created gs://${GCS_BUCKET} in $GCP_REGION"
  else
    warn "Bucket creation failed (name taken, or billing not linked)."
    SKIPPED+=("create bucket gs://${GCS_BUCKET}")
  fi
fi

printf '\n'
say "A lifecycle rule deleting objects after 30 days keeps a hackathon project"
say "from quietly accruing storage cost on clips nobody will play again."
warn "Do NOT add it to the bucket production uses: the promoted /demo job's audio"
warn "lives there, and judging runs 5 Oct - 6 Nov. A 30-day rule deletes it"
warn "mid-judging. deploy/gcp/deploy.sh creates its own bucket with no rule."
if confirm "Add the 30-day deletion rule (development bucket only)?"; then
  LIFECYCLE_FILE=$(mktemp)
  cat > "$LIFECYCLE_FILE" <<'JSON'
{
  "lifecycle": {
    "rule": [
      { "action": { "type": "Delete" }, "condition": { "age": 30 } }
    ]
  }
}
JSON
  gcloud storage buckets update "gs://${GCS_BUCKET}" \
    --lifecycle-file="$LIFECYCLE_FILE" >/dev/null 2>&1 \
    && note "30-day lifecycle rule applied" \
    || warn "could not apply the lifecycle rule"
  rm -f "$LIFECYCLE_FILE"
fi

write_env GCS_BUCKET "$GCS_BUCKET"
pause "Press Enter for the next stage."

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "The Gemini API key"
say "The key must belong to $GCP_PROJECT_ID — the project you just put billing"
say "on. A key from any other project is still rate-limited at 5 RPM no matter"
say "what this script did in stage 3."
printf '\n'
step "Check the 'Project' column next to your key. If it is not"
step "  $GCP_PROJECT_ID"
step "then use 'Create API key' and pick that project."
open_url "https://aistudio.google.com/apikey"
printf '\n'

ask_secret GEMINI_API_KEY "Paste the API key for ${GCP_PROJECT_ID}:"
if [[ -n "$GEMINI_API_KEY" ]]; then
  write_env GEMINI_API_KEY "$GEMINI_API_KEY"
else
  warn "No key captured; leaving whatever is already in $ENV_FILE."
fi

pause "Press Enter for the next stage."

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Application Default Credentials"
say "The Gemini SDK uses the API key above, but @google-cloud/storage and"
say "@google-cloud/text-to-speech do not — they authenticate as YOU locally,"
say "through ADC, and as the service account on Cloud Run."
printf '\n'
say "A browser window will open."
pause "Press Enter to run: gcloud auth application-default login"

if gcloud auth application-default login; then
  # Without a quota project the client libraries throw a confusing
  # "unable to determine the project" at the first call rather than at login.
  gcloud auth application-default set-quota-project "$GCP_PROJECT_ID" >/dev/null 2>&1 \
    && note "quota project set to $GCP_PROJECT_ID"
else
  warn "ADC login failed. Cloud TTS and GCS calls will fail until it succeeds."
  SKIPPED+=("gcloud auth application-default login")
fi

pause "Press Enter for the last stage."

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Prove it actually works"
say "Two real calls. The console saying 'enabled' and the app being able to use"
say "it are different claims, and only the second one survives demo day."
printf '\n'

say "1/2 · Writing a probe object to gs://${GCS_BUCKET} ..."
if printf 'setup probe\n' | gcloud storage cp - "gs://${GCS_BUCKET}/setup-probe.txt" >/dev/null 2>&1; then
  note "  ✓ bucket write succeeded"
  gcloud storage rm "gs://${GCS_BUCKET}/setup-probe.txt" >/dev/null 2>&1 || true
else
  warn "  ✗ bucket write FAILED — check billing and the bucket name"
  SKIPPED+=("verify GCS write access")
fi

printf '\n'
say "2/2 · Synthesizing one Hindi sentence with hi-IN-Chirp3-HD-Kore ..."
TTS_RESPONSE=$(curl -s -X POST \
  -H "Authorization: Bearer $(gcloud auth print-access-token 2>/dev/null)" \
  -H "x-goog-user-project: ${GCP_PROJECT_ID}" \
  -H "Content-Type: application/json" \
  --data '{
    "input": { "text": "नमस्ते, यह एक परीक्षण है।" },
    "voice": { "languageCode": "hi-IN", "name": "hi-IN-Chirp3-HD-Kore" },
    "audioConfig": { "audioEncoding": "MP3" }
  }' \
  "https://texttospeech.googleapis.com/v1/text:synthesize" 2>/dev/null || echo "")

if printf '%s' "$TTS_RESPONSE" | grep -q '"audioContent"'; then
  note "  ✓ Chirp 3 HD returned audio — the hi-IN voice in docs/research.md is real"
else
  warn "  ✗ Cloud TTS FAILED. Response:"
  note "    $(printf '%s' "$TTS_RESPONSE" | head -c 300)"
  SKIPPED+=("verify Cloud TTS synthesis")
fi

printf '\n'
pause "Press Enter for the summary."

finish

printf '  %sNext:%s\n' "$BOLD" "$RESET"
note "  npm run smoke:gemini      # proves the key + audio path end to end"
note "  docs/SPEC.md section f    # Phase 1 is the analyze stage"
printf '\n'
